[build]
    functions="functions"
    publish="dist"
    
[[redirects]]
    to="/.netlify/functions/api/:splat"
    from="/*"
    status=200
    force=true

[functions]
    external_node_modules=["express"]
    node_bundler="esbuild"